---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: mnist
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://mlflow/13/f83be08dd90c469385072e47a447b847/artifacts/model
        name: classifier
      name: default
      replicas: 1
